name: 'Attach Variable Set to HCP Terraform Workspace'
description: 'Looks up an HCP Terraform Variable Set by name and attaches it to a workspace by ID'
inputs:
  tfc_hostname:
    description: 'HCP Terraform hostname (default: https://app.terraform.io)'
    required: false
    default: 'app.terraform.io'
  tfc_organization:
    description: 'HCP Terraform organization name'
    required: true
  tfc_workspace_id:
    description: 'HCP Terraform workspace ID'
    required: true
  tfc_token:
    description: 'HCP Terraform API token'
    required: true
  var_set_name:
    description: 'Name of the variable set to associate with the workspace'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install jq
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y jq

    - name: Find Variable Set ID by Name
      id: get_var_set
      shell: bash
      env:
        TFC_TOKEN: ${{ inputs.tfc_token }}
        TFC_HOSTNAME: ${{ inputs.tfc_hostname }}
        TFC_ORGANIZATION: ${{ inputs.tfc_organization }}
        VAR_SET_NAME: ${{ inputs.var_set_name }}
      run: |
        response=$(curl -s \
          --header "Authorization: Bearer $TFC_TOKEN" \
          --header "Content-Type: application/vnd.api+json" \
          "https://$TFC_HOSTNAME/api/v2/organizations/$TFC_ORGANIZATION/variable-sets")

        var_set_id=$(echo "$response" | jq -r \
          --arg NAME "$VAR_SET_NAME" \
          '.data[] | select(.attributes.name == $NAME) | .id')

        if [[ -z "$var_set_id" || "$var_set_id" == "null" ]]; then
          echo "Variable set '$VAR_SET_NAME' not found"
          exit 1
        fi

        echo "var_set_id=$var_set_id" >> "$GITHUB_OUTPUT"

    - name: Attach Variable Set to Workspace
      shell: bash
      env:
        TFC_TOKEN: ${{ inputs.tfc_token }}
        TFC_HOSTNAME: ${{ inputs.tfc_hostname }}
        WORKSPACE_ID: ${{ inputs.tfc_workspace_id }}
        VAR_SET_ID: ${{ steps.get_var_set.outputs.var_set_id }}
      run: |
        payload=$(jq -n \
          --arg ws_id "$WORKSPACE_ID" \
          '{
            data: {
              type: "variable-set-relationships",
              relationships: {
                workspace: {
                  data: {
                    id: $ws_id,
                    type: "workspaces"
                  }
                }
              }
            }
          }')

        curl -s -X POST \
          --header "Authorization: Bearer $TFC_TOKEN" \
          --header "Content-Type: application/vnd.api+json" \
          --data "$payload" \
          "https://$TFC_HOSTNAME/api/v2/variable-sets/$VAR_SET_ID/relationships/workspaces"

    - name: Verify Variable Set Attached to Workspace
      shell: bash
      env:
        TFC_TOKEN: ${{ inputs.tfc_token }}
        TFC_HOSTNAME: ${{ inputs.tfc_hostname }}
        WORKSPACE_ID: ${{ inputs.tfc_workspace_id }}
        VAR_SET_ID: ${{ steps.get_var_set.outputs.var_set_id }}
      run: |
        response=$(curl -s \
          --header "Authorization: Bearer $TFC_TOKEN" \
          --header "Content-Type: application/vnd.api+json" \
          "https://$TFC_HOSTNAME/api/v2/variable-sets/$VAR_SET_ID/relationships/workspaces")

        attached=$(echo "$response" | jq -r \
          --arg ws_id "$WORKSPACE_ID" \
          '.data[]? | select(.id == $ws_id) | .id')

        if [[ "$attached" == "$WORKSPACE_ID" ]]; then
          echo "✅ Variable set successfully attached to workspace."
        else
          echo "❌ Failed to verify variable set attachment."
          echo "Response: $response"
          exit 1
        fi
